### PR TITLE
Fixed Endurain authentication

### LINKED ISSUE #1300: Adding Endurain account in RunnerUp doesn't seem to do anything
Hi, thanks for your work on this lovely FOSS app..

I am experiencing an issue when trying to add an Endurain account in RunnerUp. And I cannot figure out what to do.

- Endurain: v0.16.3
- RunnerUp: v2.9.0.6 (Android)

Steps to reproduce:
1. Open RunnerUp and go to the account connection screen.
2. Select **Endurain**.
3. Enter Website (HTTPS URL of my Endurain instance), Username, and Password.
4. Tap **OK**.

Observed behavior:
- The dialog closes, but no account is added and no error message is shown. The account list remains empty.

Additional details:
- The Endurain URL used in RunnerUp is reachable via HTTPS in a browser on the same Android device.

Is there anything else that should be configured on the Endurain or RunnerUp side, or any way to obtain logs to see why the account is not being created? 

I would love to see them working together.

### PR DESCRIPTION
**Pull request by sebastianeder1**
Fixes #1300 since endurain changed authentication: token endpoint changed from /api/v1/token to /api/v1/auth/login. See https://docs.endurain.com/developer-guide/authentication/#core-authentication-endpoints for references...

### CODE REVIEW

File: app/src/main/org/runnerup/export/EndurainSynchronizer.java [hunk 1]
```diff
@@ -171,7 +171,7 @@ public Status connect() {
       OkHttpClient client = getAuthClient();
       RequestBody formBody =
           new FormBody.Builder()
-              .add("grant_type", "password")
+              // .add("grant_type", "password")
```
Comment (gerhardol) [inline app/src/main/org/runnerup/export/EndurainSynchronizer.java]: remove is not needed

**Review by gerhardol — COMMENTED** [review]
Any other user to confirm, not using Endurain myself?

**Review by gerhardol — APPROVED** [review]

**Comment by khizirsiddiqui** [comment]
I am experiencing the same issue, would appreciate if this gets merged. I can test if you can send the apk. Thanks for the efforts!

**Comment by khizirsiddiqui** [comment]
Accidently deleted the old comment, to confirm, I am experiencing the same issue and unable to connect to Endurain. Thanks for the efforts!

**Comment by RiX012** [comment]
Same here. Thank for fixing this!
